### ISSUE TITLE
[Bug]: 编辑文字或者复习卡片的时候，obsidian会卡顿 （1.12.5.13）

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/obsidian-spaced-repetition-recall#92]
### Describe the bug

如题。obsidian会卡顿，无法编辑，无法退出。
个人觉得这个卡顿非常影响使用体验的。如果是单纯点击复习时有卡顿，因心里有预期，所以时可以接受。现在感觉是随机卡顿，有时正在打字，突然就无法输入了。其他软件是正常交互的。如果关闭目前的插件，卡顿就会消失的。

另外，点击开始复习时，obsidian会出现以下报错
```html
app.js:1 TypeError: Cannot read properties of undefined (reading 'editor')
    at t.get (app.js:1:2091356)
    at getEditorFromState (plugin:obsidian-outliner:88:13)
    at VerticalLinesPluginValue.waitForEditor (plugin:obsidian-outliner:2552:28)
    at new VerticalLinesPluginValue (plugin:obsidian-outliner:2602:14)
    at e.eval [as create] (plugin:obsidian-outliner:2795:82)
    at e.update (app.js:1:367539)
    at e.setState (app.js:1:468006)
    at t.clear (app.js:1:1378062)
    at t.clear (app.js:1:2086260)
    at t [as constructor] (app.js:1:1374961)
```

### To Reproduce

正常使用。

### Expected behavior

不卡顿。

### OS of your device

Win 10

### Obsidian version

1.1.9

### Plugin version

1.12.5.13

### Config file

[data.json](https://github.com/user-attachments/files/17986464/data.json)

**Comment by dryezl** [comment]
我打算降低版本，请问有没有对应版本推荐呢？
😂今天又碰到卡顿了

**Comment by Newdea** [comment]
这个报错是大纲插件报的。
每版都有更新记录，你看要用哪版了，推荐还是最新的🤣

**Comment by dryezl** [comment]
关闭outliner之后，报错就消除了。
另外我觉得卡顿应该是来源于插件对卡片和笔记进行索引。卡顿之后console显示插件开始了索引。
请问现在的索引是默认为触发式吗？还是需要设置呢？
如果需要设置的话，请问是哪个设置呢？我找了一遍，没有找到相应的设置。

**Comment by Undermood** [comment]
最新版本卡顿的厉害啊。和文件太多有关系吗？

**Comment by dryezl** [comment]
我自己加了一个反馈，知道大概什么时候会停止卡住的
流程是打开调试框（Ctrl + Shift + i），输入下面代码
```javascript
// write a loop, log 1 every 0.5 second
setInterval(() => {
  console.log(1);
}, 500);
```

NB： 我不知道该怎么结束上面的循环，所以目前是重启以结束循环，请谨慎使用。

**Comment by Newdea** [comment]
@dryezl 有确定大概是在什么位置卡住么。
或上传下data.json配置文件，目前我理解可能卡顿的原因：
1. 数据还是在笔记文件上保存，使用的是原算法，笔记文件多了后肯定会卡。但感觉大家应该都切换fsrs算法了，只会在刚启动时有点卡顿感吧；
2. 就是刚启动ob的卡顿，和同步时的卡顿，这个有些无法避免。除非ob能优化，因为卡片同步是要读每个文件内容，这内容由ob的api提供，如果关闭所有第三方插件，开启ob都启动慢，有卡顿感。本插件就也不可避免在同步时有点卡顿了😂

**Comment by dryezl** [comment]
[data.json](https://github.com/user-attachments/files/18344779/data.json)
以上是我的目前的data.json。
1. 我复习选择的是fsrs算法，数据是另外保存的。另外启用了block id
2. 请问同步是更新复习卡片吗？如果是的话，我是能够接受这个的。但是现在时不时就会卡住，整个obsidian一起卡住的。

我暂时确定不了具体是因为什么卡住的。

**Comment by dryezl** [comment]
![image](https://github.com/user-attachments/assets/485da009-65c0-4f80-b361-8f27066a887c)
以上是每次停止卡住之后，调试框输出的内容

**Comment by Newdea** [comment]
那就是同步的时候有点卡，本插件关闭后重启ob使用着会卡么

**Comment by dryezl** [comment]
关闭之后，无论是否重启，都不会卡的。

**Comment by dryezl** [comment]
请问这个同步的触发更新为触发式是否取消了？#83
或者说现在的同步触发是什么呢？

**Comment by Newdea** [comment]
不是同一回事，这个是遍历笔记库内文件，看是否有到期要复习的笔记或卡片，目前是每五分钟遍历一次，你可以修改main.js，改下间隔时长
这是相关代码（五分钟的）
```
this.registerInterval(
        window.setInterval(
          async () => {
            await this.sync();
          },
          5 * 60 * 1e3
        )
      );
```

**Comment by dryezl** [comment]
好的，谢谢。
我试一下把改成30分钟，看一下效果。

另外，代码显示，只有选择额外存储复习数据的时候，才会有这个同步操作。
我有点不太理解这个。如果额外存储复习数据的话，是否直接针对这个额外的数据进行检索，确认有无需要的卡片或笔记。
还是这个同步是指同步笔记或卡片的复习数据到额外的存储地方呢？
如果是这样的话，是否可以只对那些有改动的md文件进行同步，降低这个时间的？

```javascript
// line 34252 at main.js
    if (this.data.settings.dataLocation !== "Save On Note File" /* SaveOnNoteFile */) {
      this.registerInterval(
        window.setInterval(
          async () => {
            await this.sync();
          },
          30 * 60 * 1e3
        )
      );
    }
```

**Comment by dryezl** [comment]
更改遍历笔记库内文件的时间为30min后，效果不错的。现在的卡顿对我来说，基本没有什么影响的。
